### ISSUE TITLE
Cannot find dotenv

### ISSUE THREAD

**Issue by lmclarke** [gesslar/mud-discord-chat#1]
![example](https://user-images.githubusercontent.com/3780592/213261486-ce59a8bd-d0c6-4e0e-83bb-ea8313f5621e.png)
node chat.js
```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'dotenv'
```
Sorry to pester you, and for the record this has been a huge help already - I've been trying to do something like this for years, so finding your repo was a godsend.

What does this error mean/what do I need to do to resolve? I followed the instructions, but I think based on the error message I must have misunderstood what was meant by 'create a .env file'. The file I created was simply '.env' with no file type.

What file type is '.env' intended to be? Does it go in the same folder as the chat.js file? 

Directory structure/setup attached.

**Comment by gesslar** [comment]
I see that you haven't run `npm install`. When you clone a Node.js repo, you need to run that command to download all the dependencies.

```json
  "dependencies": {
    "bitly": "^7.1.2",
    "discord.js": "^12.5.3",
    "dotenv": "^9.0.2",
    "emoji-regex": "^9.2.2",
    "url-regex-safe": "^2.0.2"
  }
  ```

**Comment by lmclarke** [comment]
Thank you! Ran npm install.

As a follow-up, when executing node chat.js I get the following:

node chat.js
```
Connected to MUD amud-mud.com:1989
undefined:1
�� _____________________________________________________________________________                        _
^

SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at Socket.<anonymous> (/home/tfzmud/discord/chat.js:64:30)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

Related? Thank you for the quick response by the way!

**Comment by gesslar** [comment]
This looks like the message it received from the MUD doesn't parse to JSON.

Okay, I think I see what's happening.

Are you pointing it to the same port as your users log into? This isn't how this will work. For reference, I am on an LP mud. So, I create a daemon in the game and create a socket to listen on a specific port.

In my config.json the ` "mud_port": 8181,` is the port that the daemon is listening on from within the game. My regular game port is 3333, but I don't use that in mud-discord-chat.

**Comment by lmclarke** [comment]
Ahh, yes I was. I've changed the port to an alternative. I'm running a ROM derivative so I'm not positive how to approach the daemon aspect. The error has changed with the port switch, which is heartening.

node chat.js
```
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 144.217.205.176:1990
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '144.217.205.176',
  port: 1990
}
```
My assumption is I need to do something along the lines of what the LP MUD daemon accomplishes, but what that would be is a little beyond me. Thank you for your responses and help, it's been appreciated.

**Comment by gesslar** [comment]
Maybe someone in /r/MUD or their Discord would be able to help! I have no idea how to do ROM. I'm sorry 😭.

I am glad you found the repo and that you will likely get this all working! 🤗

**Comment by lmclarke** [comment]
It's totally okay! And will do. I think if this can structured up for ROM it would be a huge help to the MUD community in general. I'll definitely make a gist.

Cheers to you!
